-- MySQL Script generated by MySQL Workbench
-- sáb 04 feb 2023 17:44:05
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema searchemtool
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema searchemtool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `searchemtool` ;
USE `searchemtool` ;

-- -----------------------------------------------------
-- Table `searchemtool`.`organism`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `searchemtool`.`organism` (
  `taxa_id` INT(11) NOT NULL,
  `scientific_name` VARCHAR(200) NULL,
  PRIMARY KEY (`taxa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `searchemtool`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `searchemtool`.`user` (
  `user_id` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(20) NULL,
  PRIMARY KEY (`user_id`),
  INDEX `idx_last_name` (`last_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Table storing all customers. Holds foreign keys to the address table and the store table where this customer is registered.\n\nBasic information about the customer like first and last name are stored in the table itself. Same for the date the record was created and when the information was last updated.';


-- -----------------------------------------------------
-- Table `searchemtool`.`target`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `searchemtool`.`target` (
  `uniprot_id` VARCHAR(15) NOT NULL,
  `protein_name` VARCHAR(150) NULL,
  `organism_taxa_id` INT(11) NOT NULL,
  PRIMARY KEY (`uniprot_id`, `organism_taxa_id`),
  INDEX `fk_Target_Organism1_idx` (`organism_taxa_id` ASC) VISIBLE,
  CONSTRAINT `fk_Target_Organism1`
    FOREIGN KEY (`organism_taxa_id`)
    REFERENCES `searchemtool`.`organism` (`taxa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `searchemtool`.`molecule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `searchemtool`.`molecule` (
  `chembl_id` VARCHAR(15) NOT NULL,
  `name` VARCHAR(100) NULL,
  `formula` VARCHAR(100) NULL,
  `type` VARCHAR(50) NULL,
  PRIMARY KEY (`chembl_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `searchemtool`.`target_has_molecule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `searchemtool`.`target_has_molecule` (
  `target_uniprot_id` VARCHAR(15) NOT NULL,
  `molecule_chembl_id` VARCHAR(15) NOT NULL,
  `reference_id` VARCHAR(200) NULL,
  `type_of_activity` ENUM('AGONIST', 'ANTAGONIST') NULL,
  PRIMARY KEY (`target_uniprot_id`, `molecule_chembl_id`),
  INDEX `fk_Target_has_Molecule_Molecule1_idx` (`molecule_chembl_id` ASC) VISIBLE,
  INDEX `fk_Target_has_Molecule_Target1_idx` (`target_uniprot_id` ASC) VISIBLE,
  CONSTRAINT `fk_Target_has_Molecule_Target1`
    FOREIGN KEY (`target_uniprot_id`)
    REFERENCES `searchemtool`.`target` (`uniprot_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Target_has_Molecule_Molecule1`
    FOREIGN KEY (`molecule_chembl_id`)
    REFERENCES `searchemtool`.`molecule` (`chembl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `searchemtool`.`user_has_target`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `searchemtool`.`user_has_target` (
  `user_user_id` VARCHAR(50) NOT NULL,
  `target_uniprot_id` VARCHAR(6) NOT NULL,
  `target_organism_taxa_id` INT(11) NOT NULL,
  `favourite` ENUM('yes', 'no') NULL,
  PRIMARY KEY (`user_user_id`, `target_uniprot_id`, `target_organism_taxa_id`),
  INDEX `fk_user_has_target_target1_idx` (`target_uniprot_id` ASC, `target_organism_taxa_id` ASC, `favourite` ASC) VISIBLE,
  INDEX `fk_user_has_target_user1_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_target_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `searchemtool`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_target_target1`
    FOREIGN KEY (`target_uniprot_id` , `target_organism_taxa_id`)
    REFERENCES `searchemtool`.`target` (`uniprot_id` , `organism_taxa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `searchemtool`.`user_has_molecule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `searchemtool`.`user_has_molecule` (
  `user_user_id` VARCHAR(50) NOT NULL,
  `molecule_chembl_id` VARCHAR(15) NOT NULL,
  `favourite` ENUM('yes', 'no') NULL,
  `last_update` VARCHAR(45) NULL,
  PRIMARY KEY (`user_user_id`, `molecule_chembl_id`),
  INDEX `fk_user_has_molecule_molecule1_idx` (`molecule_chembl_id` ASC, `favourite` ASC) VISIBLE,
  INDEX `fk_user_has_molecule_user1_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_molecule_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `searchemtool`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_molecule_molecule1`
    FOREIGN KEY (`molecule_chembl_id`)
    REFERENCES `searchemtool`.`molecule` (`chembl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `searchemtool`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `searchemtool`.`provider` (
  `provider_id` INT(11) NOT NULL,
  `provider_name` VARCHAR(45) NULL,
  PRIMARY KEY (`provider_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `searchemtool`.`molecule_has_provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `searchemtool`.`molecule_has_provider` (
  `molecule_chembl_id` VARCHAR(15) NOT NULL,
  `providers_provider_id` INT(11) NOT NULL,
  PRIMARY KEY (`molecule_chembl_id`, `providers_provider_id`),
  INDEX `fk_molecule_has_providers_providers1_idx` (`providers_provider_id` ASC) VISIBLE,
  INDEX `fk_molecule_has_providers_molecule1_idx` (`molecule_chembl_id` ASC) VISIBLE,
  CONSTRAINT `fk_molecule_has_providers_molecule1`
    FOREIGN KEY (`molecule_chembl_id`)
    REFERENCES `searchemtool`.`molecule` (`chembl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_molecule_has_providers_providers1`
    FOREIGN KEY (`providers_provider_id`)
    REFERENCES `searchemtool`.`provider` (`provider_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `searchemtool` ;

-- -----------------------------------------------------
-- procedure rewards_report
-- -----------------------------------------------------

DELIMITER $$
USE `searchemtool`$$


CREATE PROCEDURE `searchemtool`.`rewards_report` (
    IN min_monthly_purchases TINYINT UNSIGNED
    , IN min_dollar_amount_purchased DECIMAL(10,2) UNSIGNED
    , OUT count_rewardees INT
)
LANGUAGE SQL
NOT DETERMINISTIC 
READS SQL DATA
SQL SECURITY DEFINER
COMMENT 'Provides a customizable report on best customers'
proc: BEGIN
    
    DECLARE last_month_start DATE;
    DECLARE last_month_end DATE;

    /* Some sanity checks... */
    IF min_monthly_purchases = 0 THEN
        SELECT 'Minimum monthly purchases parameter must be > 0';
        LEAVE proc;
    END IF;
    IF min_dollar_amount_purchased = 0.00 THEN
        SELECT 'Minimum monthly dollar amount purchased parameter must be > $0.00';
        LEAVE proc;
    END IF;

    /* Determine start and end time periods */
    SET last_month_start = DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH);
    SET last_month_start = STR_TO_DATE(CONCAT(YEAR(last_month_start),'-',MONTH(last_month_start),'-01'),'%Y-%m-%d');
    SET last_month_end = LAST_DAY(last_month_start);

    /* 
        Create a temporary storage area for 
        Customer IDs.  
    */
    CREATE TEMPORARY TABLE tmpCustomer (customer_id SMALLINT UNSIGNED NOT NULL PRIMARY KEY);

    /* 
        Find all customers meeting the 
        monthly purchase requirements
    */
    INSERT INTO tmpCustomer (customer_id)
    SELECT p.customer_id 
    FROM payment AS p
    WHERE DATE(p.payment_date) BETWEEN last_month_start AND last_month_end
    GROUP BY customer_id
    HAVING SUM(p.amount) > min_dollar_amount_purchased
    AND COUNT(customer_id) > min_monthly_purchases;

    /* Populate OUT parameter with count of found customers */
    SELECT COUNT(*) FROM tmpCustomer INTO count_rewardees;

    /* 
        Output ALL customer information of matching rewardees.
        Customize output as needed.
    */
    SELECT c.* 
    FROM tmpCustomer AS t   
    INNER JOIN customer AS c ON t.customer_id = c.customer_id;

    /* Clean up */
    DROP TABLE tmpCustomer;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function get_customer_balance
-- -----------------------------------------------------

DELIMITER $$
USE `searchemtool`$$


CREATE FUNCTION `searchemtool`.`get_customer_balance`(p_customer_id INT, p_effective_date DATETIME) RETURNS DECIMAL(5,2)
    DETERMINISTIC
    READS SQL DATA
BEGIN

       #OK, WE NEED TO CALCULATE THE CURRENT BALANCE GIVEN A CUSTOMER_ID AND A DATE
       #THAT WE WANT THE BALANCE TO BE EFFECTIVE FOR. THE BALANCE IS:
       #   1) RENTAL FEES FOR ALL PREVIOUS RENTALS
       #   2) ONE DOLLAR FOR EVERY DAY THE PREVIOUS RENTALS ARE OVERDUE
       #   3) IF A FILM IS MORE THAN RENTAL_DURATION * 2 OVERDUE, CHARGE THE REPLACEMENT_COST
       #   4) SUBTRACT ALL PAYMENTS MADE BEFORE THE DATE SPECIFIED

  DECLARE v_rentfees DECIMAL(5,2); #FEES PAID TO RENT THE VIDEOS INITIALLY
  DECLARE v_overfees INTEGER;      #LATE FEES FOR PRIOR RENTALS
  DECLARE v_payments DECIMAL(5,2); #SUM OF PAYMENTS MADE PREVIOUSLY

  SELECT IFNULL(SUM(film.rental_rate),0) INTO v_rentfees
    FROM film, inventory, rental
    WHERE film.film_id = inventory.film_id
      AND inventory.inventory_id = rental.inventory_id
      AND rental.rental_date <= p_effective_date
      AND rental.customer_id = p_customer_id;

  SELECT IFNULL(SUM(IF((TO_DAYS(rental.return_date) - TO_DAYS(rental.rental_date)) > film.rental_duration,
        ((TO_DAYS(rental.return_date) - TO_DAYS(rental.rental_date)) - film.rental_duration),0)),0) INTO v_overfees
    FROM rental, inventory, film
    WHERE film.film_id = inventory.film_id
      AND inventory.inventory_id = rental.inventory_id
      AND rental.rental_date <= p_effective_date
      AND rental.customer_id = p_customer_id;


  SELECT IFNULL(SUM(payment.amount),0) INTO v_payments
    FROM payment

    WHERE payment.payment_date <= p_effective_date
    AND payment.customer_id = p_customer_id;

  RETURN v_rentfees + v_overfees - v_payments;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function inventory_held_by_customer
-- -----------------------------------------------------

DELIMITER $$
USE `searchemtool`$$


CREATE FUNCTION `searchemtool`.`inventory_held_by_customer`(p_inventory_id INT) RETURNS INT
READS SQL DATA
BEGIN
  DECLARE v_customer_id INT;
  DECLARE EXIT HANDLER FOR NOT FOUND RETURN NULL;

  SELECT customer_id INTO v_customer_id
  FROM rental
  WHERE return_date IS NULL
  AND inventory_id = p_inventory_id;

  RETURN v_customer_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function inventory_in_stock
-- -----------------------------------------------------

DELIMITER $$
USE `searchemtool`$$


CREATE FUNCTION `searchemtool`.`inventory_in_stock`(p_inventory_id INT) RETURNS BOOLEAN
READS SQL DATA
BEGIN
    DECLARE v_rentals INT;
    DECLARE v_out     INT;

    #AN ITEM IS IN-STOCK IF THERE ARE EITHER NO ROWS IN THE rental TABLE
    #FOR THE ITEM OR ALL ROWS HAVE return_date POPULATED

    SELECT COUNT(*) INTO v_rentals
    FROM rental
    WHERE inventory_id = p_inventory_id;

    IF v_rentals = 0 THEN
      RETURN TRUE;
    END IF;

    SELECT COUNT(rental_id) INTO v_out
    FROM inventory LEFT JOIN rental USING(inventory_id)
    WHERE inventory.inventory_id = p_inventory_id
    AND rental.return_date IS NULL;

    IF v_out > 0 THEN
      RETURN FALSE;
    ELSE
      RETURN TRUE;
    END IF;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
